### ISSUE TITLE
NABirds Dataset

### ISSUE THREAD

**Issue by WangYZ1608** [mingzeG/Moment-Probing#1]
Hello. 
Congratulations on your great paper !
I'm having some trouble downloading the NABirds dataset, Can you release this dataset?
Looking forward to your reply.

**Comment by mingzeG** [comment]
Hei, you could download from the official link below
https://dl.allaboutbirds.org/nabirds

Or download NABirds from the provided google drive in 
https://github.com/KMnP/vpt?tab=readme-ov-file
